package com.example.demo.model;

public class Tips {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPS.ID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPS.STATUS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPS.USERID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPS.QUESTIONID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    private Long questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPS.TYPE
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPS.ID
     *
     * @return the value of TIPS.ID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPS.ID
     *
     * @param id the value for TIPS.ID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPS.STATUS
     *
     * @return the value of TIPS.STATUS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPS.STATUS
     *
     * @param status the value for TIPS.STATUS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPS.USERID
     *
     * @return the value of TIPS.USERID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPS.USERID
     *
     * @param userid the value for TIPS.USERID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPS.QUESTIONID
     *
     * @return the value of TIPS.QUESTIONID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPS.QUESTIONID
     *
     * @param questionid the value for TIPS.QUESTIONID
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPS.TYPE
     *
     * @return the value of TIPS.TYPE
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPS.TYPE
     *
     * @param type the value for TIPS.TYPE
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}