package com.example.demo.mapper;

import com.example.demo.model.Tips;
import com.example.demo.model.TipsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    long countByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int deleteByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int insert(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int insertSelective(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    List<Tips> selectByExampleWithRowbounds(TipsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    List<Tips> selectByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    Tips selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tips record, @Param("example") TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int updateByExample(@Param("record") Tips record, @Param("example") TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int updateByPrimaryKeySelective(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPS
     *
     * @mbg.generated Fri May 01 16:41:13 CST 2020
     */
    int updateByPrimaryKey(Tips record);
}